### PR TITLE
Use `cross-spawn` by default

### LINKED ISSUE #11: `spawn ENOENT` on Windows
Trying to spawn `elm-make` on Windows results in a `NOENT` error, even if your `PATH` is correctly configured to look in the `npm` folder. I believe this is caused by this issue on Node: https://github.com/nodejs/node-v0.x-archive/issues/2318

Using something like [`cross-spawn`](https://www.npmjs.com/package/cross-spawn) should solve the issue.

### PR DESCRIPTION
**Pull request by unindented**
Fixes #11.

### CODE REVIEW

**Comment by eeue56** [comment]
I agree with this - it looks good to me and the docs seem to suggest this is the nicest way to have this supported cross-platform. 

@rtfeldman, can you merge this so that it unblocks https://github.com/rtfeldman/elm-webpack-loader/pull/12 ?

**Comment by rtfeldman** [comment]
@unindented I added a test on master that reproduces the bug; it passes Travis but fails AppVeyor. Unfortunately it also introduced a merge conflict here, but once that's resolved this should be good to merge!

**Comment by unindented** [comment]
@rtfeldman Awesome, thanks for adding those tests! The conflict is resolved, and the tests are passing. 🎉

**Comment by rtfeldman** [comment]
Published as 2.2.0 @unindented @eeue56

**Pull request merged**
